conditional_message.settings:
  type: mapping
  label: Settings
  mapping:
    conditional_message_options:
      type: 'NULL'
    conditional_message_text:
      type: string
    conditional_message_bg_color:
      type: color_hex
    conditional_message_color:
      type: color_hex
    conditional_message_position:
      type: string
    conditional_message_target:
      type: string
